### ISSUE TITLE
Import of repository failing on launchpad

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose-full#3]
This repo is imported on launchpad for creating packages in PPA [ppa:bhallalab/moose](https://launchpad.net/~bhallalab/+archive/ubuntu/moose). The import has stopped due to [some issue in bzr](https://code.launchpad.net/~bhallalab/moogli/trunk). 

So I use the github repo to update the native [bzr repo in launchpad](https://code.launchpad.net/~bhallalab/moogli/trunk). One needs to update the bzr repo periodically till github  imports are back on track.

**Comment by dilawar** [comment]
bzr brach lp:mooose
     cd moose
      git remote add origin https://github.com/BhallaLab/moose-full

And then merge them. Care should be taken when running `git clean` etc command which might delete files unknown to git or bzr.

**Comment by dilawar** [comment]
The trace-back of problem:

~~~
Using saved push location: bzr+ssh://bazaar.launchpad.net/+branch/moogli/
bzr: ERROR: bzrlib.errors.InvalidEntryName: Invalid entry name: \                                    

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bzrlib/commands.py", line 930, in exception_to_return_code
    return the_callable(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bzrlib/commands.py", line 1121, in run_bzr
    ret = run(*run_argv)
  File "/usr/lib/python2.7/dist-packages/bzrlib/commands.py", line 673, in run_argv_aliases
    return self.run(**all_cmd_args)
  File "/usr/lib/python2.7/dist-packages/bzrlib/commands.py", line 697, in run
    return self._operation.run_simple(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bzrlib/cleanup.py", line 136, in run_simple
    self.cleanups, self.func, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bzrlib/cleanup.py", line 166, in _do_with_cleanups
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bzrlib/builtins.py", line 1393, in run
    use_existing_dir=use_existing_dir, no_tree=no_tree)
  File "/usr/lib/python2.7/dist-packages/bzrlib/push.py", line 146, in _show_push_branch
    remember, create_prefix)
  File "/usr/lib/python2.7/dist-packages/bzrlib/controldir.py", line 431, in push_branch
    overwrite, stop_revision=revision_id)
  File "/usr/lib/python2.7/dist-packages/bzrlib/branch.py", line 1120, in push
    lossy, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bzrlib/branch.py", line 3331, in push
    _override_hook_source_branch=_override_hook_source_branch)
  File "/usr/lib/python2.7/dist-packages/bzrlib/cleanup.py", line 132, in run
    self.cleanups, self.func, self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bzrlib/cleanup.py", line 166, in _do_with_cleanups
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/bzrlib/branch.py", line 3389, in _push_with_bound_branches
    result = self._basic_push(overwrite, stop_revision)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/git/branch.py", line 856, in _basic_push
    stop_revision, overwrite=overwrite)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/git/branch.py", line 752, in _update_revisions
    head, refs = self.fetch_objects(stop_revision, fetch_tags=None)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/git/branch.py", line 745, in fetch_objects
    determine_wants, self.source.mapping, limit=limit)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/git/fetch.py", line 755, in fetch_objects
    target_git_object_retriever, wants, pb, limit)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/git/fetch.py", line 516, in import_git_objects
    target_git_object_retriever, trees_cache)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/git/fetch.py", line 409, in import_git_commit
    False))
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/git/fetch.py", line 298, in import_git_tree
    lookup_file_id, allow_submodules=allow_submodules)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/git/fetch.py", line 312, in import_git_tree
    (child_base_mode, child_mode), store_updater, lookup_file_id)
  File "/usr/lib/python2.7/dist-packages/bzrlib/plugins/git/fetch.py", line 119, in import_git_blob
    ie = cls(file_id, name.decode("utf-8"), parent_id)
  File "/usr/lib/python2.7/dist-packages/bzrlib/inventory.py", line 422, in __init__
    super(InventoryFile, self).__init__(file_id, name, parent_id)
  File "/usr/lib/python2.7/dist-packages/bzrlib/inventory.py", line 222, in __init__
    raise errors.InvalidEntryName(name=name)
InvalidEntryName: Invalid entry name: \

bzr 2.7.0dev1 on python 2.7.6 (Linux-3.16.0-49-generic-x86_64-with-
    Ubuntu-14.04-trusty)
arguments: ['/usr/bin/bzr', 'push']
plugins: bash_completion[2.7.0dev1], changelog_merge[2.7.0dev1],
    fastimport[0.14.0dev], git[0.6.12], grep[2.7.0dev1], launchpad[2.7.0dev1],
    netrc_credential_store[2.7.0dev1], news_merge[2.7.0dev1],
    po_merge[2.7.0dev1], weave_fmt[2.7.0dev1]
encoding: 'utf-8', fsenc: 'UTF-8', lang: 'en_US.UTF-8'
~~~

**Comment by dilawar** [comment]
recreated the repository. This seems to be fixed now.
